### ISSUE TITLE
Please use new string formatting

### ISSUE THREAD

**Issue by m-rey** [tomschr/leo#13]
Currently, to format strings, the [old way of formatting strings](https://docs.python.org/3/library/stdtypes.html#old-string-formatting) is used. It would be great to change this to a newer way of doing it, like using [format()](https://docs.python.org/3/library/stdtypes.html#str.format).

The website https://pyformat.info/ may be helpful.

**Comment by tomschr** [comment]
@m-rey Thanks Martin for your idea! :+1: 

You have a specific line in your mind? If you think of these `log.debug` lines, these are an exception. :wink: This is done to allow lazy evaluation.

However, you can change that with the `style` parameter in the [logging.basicConfig](https://docs.python.org/3/library/logging.html#logging.basicConfig), allowing to switch from old-style to new-style. However, I was a bit lazy to apply that to all the logging functions. :wink: 

Is that what you mean?

**Comment by m-rey** [comment]
That's exactly what I was referring to!

I was confused about the logging style at first, but now it makes sense.

Thanks for clearing things up :)
